### ISSUE TITLE
黄金规则1-3，PPT 11-14

### ISSUE THREAD

**Issue by bwcao** [sebuaa2020/Team202#2]

**Comment by Lisawbw** [comment]
【**置于用户控制之下：**
提示窗口；机器人执行动作时的反馈
**减少用户负担：**
四种模式清晰的展示在页面上
**保持界面一致：**
运用弹出对话框形式，免除了负面之间的切换】
目前大概想的是这样，不过在文档中应该以什么方式撰写好一点呢？

**Comment by bwcao** [comment]
我觉得这样的设计很好，后续还应随时补充。
建议你首先在用户界面分析部分结合黄金规则和课程要求阐释你的设计理念和设计思路，而后在用户界面设计部分结合具体界面指出你是如何实现这些内容的。
