### ISSUE TITLE
关于STD修改方案的几点疑惑

### ISSUE THREAD

**Issue by bwcao** [sebuaa2020/Team202#3]
测试用例仍然以表格形式呈现，还是每个用例一小节分开展示呢？

**Comment by Lisawbw** [comment]
是不是分开好一点呀，表格列数太多显得有点臃肿

**Comment by quanql** [comment]
或者如果还用表格就把表格横过来

**Comment by quanql** [comment]
不过还是每个用例分开展示更好一些

**Comment by bwcao** [comment]
都有道理。
此外，是否需要在每个模块中声明选取用例的原因/标准？

**Comment by Lisawbw** [comment]
嗯嗯，应该需要吧，增强了用例的可信度和完整性？

**Comment by Ace0001** [comment]
嗯嗯，感觉可以对于每个模块增添相应测试策略的原因
